config/routes.rb
Rails.application.routes.draw do

  get 'teachers/ranking' => 'teachers#ranking'
  get 'teachers/:id/vote' => 'teachers#vote', as: 'rate'
  root :to => 'teachers#ranking'

  resources :votes

  resources :teachers
  
  devise_for :users

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :votes
  
  def to_s
    first_name + " " + last_name
  end
  
  def knowledge_sharing
    if votes.size > 0
      ((votes.inject(0) { |sum, vote| sum + vote.knowledge_sharing }).to_f /
        votes.size).round(2)
    else
      0
    end
  end
  
  def passing_difficulty
    if votes.size > 0
      ((votes.inject(0) { |sum, vote| sum + vote.passing_difficulty }).to_f /
        votes.size).round(2)
    else
      0
    end
  end
  
  def justice
    if votes.size > 0
      ((votes.inject(0) { |sum, vote| sum + vote.justice }).to_f /
        votes.size).round(2)
    else
      0
    end
  end
  
  def jokes_level
    if votes.size > 0
      ((votes.inject(0) { |sum, vote| sum + vote.jokes_level }).to_f /
        votes.size).round(2)
    else
      0
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :votes
  
  def to_s
    email
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def authenticate_user!
    if user_signed_in?
      super     
    else
      redirect_to new_user_session_path,
        :notice => 'You must be logged in to access this page.'
    end
  end
  
  def authenticate_admin!
    if user_signed_in? && current_user.is_admin
      authenticate_user!
    else
      redirect_to root_path,
        :notice => 'Only administrator can access this page.'
    end
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_filter :authenticate_admin!, except: [:ranking, :vote]
  before_filter :authenticate_user!, only: [:vote]
  before_action :set_teacher, only: [:show, :edit, :vote, :update, :destroy]

  respond_to :html

  def index
    @teachers = Teacher.all
    respond_with(@teachers)
  end
  
  def ranking
    @teachers = Teacher.all
    respond_with(@teachers)
  end

  def show
    respond_with(@teacher)
  end

  def new
    @teacher = Teacher.new
    respond_with(@teacher)
  end
  
  def vote
    @vote = @teacher.votes.find_by_user_id(current_user.id)
    if @vote.nil?
      @vote = Vote.new
    end
    respond_to do |format|
      format.html { render :layout => false }
    end
  end

  def edit
  end

  def create
    @teacher = Teacher.new(teacher_params)
    @teacher.save
    respond_with(@teacher)
  end

  def update
    @teacher.update(teacher_params)
    respond_with(@teacher)
  end

  def destroy
    @teacher.destroy
    respond_with(@teacher)
  end

  private
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    def teacher_params
      params.require(:teacher).permit(:first_name, :last_name)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @votes = Vote.all
    respond_with(@votes)
  end

  def show
    respond_with(@vote)
  end

  def new
    @vote = Vote.new
    respond_with(@vote)
  end

  def edit
  end

  def create
    @vote = VoteForm.new(vote_params)
    @vote.user_id = current_user.id
    respond_to do |format|
      if @vote.save
        format.html do
          redirect_to root_url
        end
      end
    end
  end

  def update
    @vote.update(vote_params)
    respond_with(@vote)
  end

  def destroy
    @vote.destroy
    respond_with(@vote)
  end

  private
    def set_vote
      @vote = Vote.find(params[:id])
    end

    def vote_params
      params.require(:vote).permit(:knowledge_sharing, :passing_difficulty, :justice, :jokes_level, :teacher_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rate_helper.rb
module RateHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RateTeachers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="header">
  <span class="left">
  <%= link_to 'Rate teachers', root_url, :class => 'header-link' %>
  <% if user_signed_in? && current_user.is_admin %>
    <%= link_to 'Votes (admin)', votes_url, :class => 'header-link' %>
    <%= link_to 'Teachers (admin)', teachers_url, :class => 'header-link' %>
  <% end %>
  </span>

  <span class="right">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'header-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'header-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'header-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'header-link'  %>
  <% end %>
  </span>
</div>

<div id="content">
<%= yield %>
</div>

</body>
</html>

app/views/rate/index.html.erb
<h1>Rate teachers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Knowledge sharing</th>
      <th>Passing difficulty</th>
      <th>Justice</th>
      <th>Jokes level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.first_name %></td>
        <td><%= teacher.last_name %></td>
        <td><%= teacher.knowledge_sharing %></td>
        <td><%= teacher.passing_difficulty %></td>
        <td><%= teacher.justice %></td>
        <td><%= teacher.jokes_level %></td>
        <td><%= link_to 'Vote', rate_path(teacher) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/_rate_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.hidden_field :teacher_id, :value => @teacher.id %>
  
  <div class="field">
    <%= f.label :knowledge_sharing %><br>
    <%= f.select :knowledge_sharing, ((1..5).map {|i| [i,i] }) %>
  </div>
  <div class="field">
    <%= f.label :passing_difficulty %><br>
    <%= f.select :passing_difficulty, ((1..5).map {|i| [i,i] }) %>
  </div>
  <div class="field">
    <%= f.label :justice %><br>
    <%= f.select :justice, ((1..5).map {|i| [i,i] }) %>
  </div>
  <div class="field">
    <%= f.label :jokes_level %><br>
    <%= f.select :jokes_level, ((1..5).map {|i| [i,i] }) %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<h1>Listing teachers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Knowledge sharing</th>
      <th>Passing difficulty</th>
      <th>Justice</th>
      <th>Jokes level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.first_name %></td>
        <td><%= teacher.last_name %></td>
        <td><%= teacher.knowledge_sharing %></td>
        <td><%= teacher.passing_difficulty %></td>
        <td><%= teacher.justice %></td>
        <td><%= teacher.jokes_level %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/teachers/ranking.html.erb
<h1>Rate teachers</h1>

<div id="ranking">
<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Knowledge sharing</th>
      <th>Passing difficulty</th>
      <th>Justice</th>
      <th>Jokes level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.first_name %></td>
        <td><%= teacher.last_name %></td>
        <td><%= teacher.knowledge_sharing %></td>
        <td><%= teacher.passing_difficulty %></td>
        <td><%= teacher.justice %></td>
        <td><%= teacher.jokes_level %></td>
        <% if user_signed_in? %>
          <td><button class="rate" id="<%=teacher.id.to_s %>">Rate</button></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
</div>

<div id="rate-frame">

</div>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @teacher.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @teacher.last_name %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/vote.html.erb
<h3>You are rating teacher: <%= @teacher %></h3>

<%= render 'rate_form' %>

app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :knowledge_sharing %><br>
    <%= f.number_field :knowledge_sharing %>
  </div>
  <div class="field">
    <%= f.label :passing_difficulty %><br>
    <%= f.number_field :passing_difficulty %>
  </div>
  <div class="field">
    <%= f.label :justice %><br>
    <%= f.number_field :justice %>
  </div>
  <div class="field">
    <%= f.label :jokes_level %><br>
    <%= f.number_field :jokes_level %>
  </div>
  <div class="field">
    <%= f.label :teacher_id %><br>
    <%= f.text_field :teacher_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<h1>Listing votes</h1>

<table>
  <thead>
    <tr>
      <th>Knowledge sharing</th>
      <th>Passing difficulty</th>
      <th>Justice</th>
      <th>Jokes level</th>
      <th>Teacher</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.knowledge_sharing %></td>
        <td><%= vote.passing_difficulty %></td>
        <td><%= vote.justice %></td>
        <td><%= vote.jokes_level %></td>
        <td><%= vote.teacher %></td>
        <td><%= vote.user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/votes/new.html.erb
<h1>New vote</h1>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<h1>Your vote:</h1>

<p>
  <strong>Teacher:</strong>
  <%= @vote.teacher %>
</p>

<p>
  <strong>Knowledge sharing:</strong>
  <%= @vote.knowledge_sharing %>
</p>

<p>
  <strong>Passing difficulty:</strong>
  <%= @vote.passing_difficulty %>
</p>

<p>
  <strong>Justice:</strong>
  <%= @vote.justice %>
</p>

<p>
  <strong>Jokes level:</strong>
  <%= @vote.jokes_level %>
</p>

<%= link_to 'Edit', rate_path(@vote.teacher)%> |
<%= link_to 'Back', root_path%>